// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-courantes'}],
  tp: [{type: 'autogenerated', dirName: '02-passees'}],
};

module.exports = sidebars;
