// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  rubriques: [{ type: "autogenerated", dirName: "01-rubriques" }],
  capsulesCourantes: [
    { type: "autogenerated", dirName: "02-capsules-courantes" },
  ],
  capsulesPassees: [{ type: "autogenerated", dirName: "03-capsules-passees" }],
};

module.exports = sidebars;
